version: '3'
services:
  electrumx:
    build:
      context: ./
    container_name: electrumx-testnet
    depends_on:
      - bitcoind
    image: chainbow/electrumx:${APP_VER}
    environment:
      - DAEMON_URL=bitcoin:password@bitcoind:18332
      - NET=testnet
      - COIN=Bitcoin
      - SERVICES=ssl://0.0.0.0:51002,tcp://0.0.0.0:51001
      - REPORT_SERVICES=ssl://${DOMAIN}:51002,tcp://${DOMAIN}:51001
    ports:
      - "51002:51002"
      - "51001:51001"
    networks:
      - electrumx-testnet-network
    volumes:
      - ./data/electrumx:/data
    restart: always
  bitcoind:
    image: 'ruimarinho/bitcoin-core:latest'
    container_name: bitcoind-testnet
    ports:
      # change to 18333 if running testnet
      - '18333:18333'
      # JSON-RPC
      - '18332:18332'
    networks:
      - electrumx-testnet-network
    volumes:
      - ./data/bitcoin:/home/bitcoin/.bitcoin
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
    command: bitcoind 
    restart: always
networks:
  electrumx-testnet-network: