version: '3'
services:
  electrumx:
    build:
      context: ./
    container_name: electrumx
    depends_on:
      - bitcoind
    image: chainbow/electrumx:${APP_VER}
    environment:
      - DAEMON_URL=bitcoin:password@bitcoind:8332
      - NET=mainnet
      - COIN=Bitcoin
      - SERVICES=ssl://0.0.0.0:50002,tcp://0.0.0.0:50001
      - REPORT_SERVICES=ssl://${DOMAIN}:50002,tcp://${DOMAIN}:50001
    ports:
      - "50002:50002"
      - "50001:50001"
      - "50004:50004"
    networks:
      - electrumx-network
    volumes:
      - ./data/electrumx:/data
    restart: always
  bitcoind:
    image: 'ruimarinho/bitcoin-core:latest'
    container_name: bitcoind
    ports:
      # change to 18333 if running testnet
      - '8333:8333'
    #   # JSON-RPC
    #   - '8332:8332'
    #   # ZMQ
    #   - '28332:28332'
    networks:
      - electrumx-network
    volumes:
      - ./data/bitcoin:/home/bitcoin/.bitcoin
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
    command: bitcoind 
    restart: always
networks:
  electrumx-network: