version: '3'
services:
  electrumx:
    build:
      context: ./
    container_name: electrumx
    depends_on:
      - bitcoind
    image: chainbow/electrumx:${APP_VER}
    environment:
      - DAEMON_URL=bitcoin:password@bitcoind
      - COIN=BitcoinSV
      - SERVICES=ssl://0.0.0.0:50002,tcp://0.0.0.0:50001
      - REPORT_SERVICES=ssl://${DOMAIN}:50002,tcp://${DOMAIN}:50001
    ports:
      - "50002:50002"
      - "50001:50001"
      - "50004:50004"
    networks:
      - electrumx-network
    volumes:
      - ./data/electrumx:/data
    restart: always
  bitcoind:
    image: 'bitcoinsv/bitcoin-sv:latest'
    container_name: bitcoind
    ports:
      # change to 18333 if running testnet
      - '8333:8333'
      # JSON-RPC
      - '8332:8332'
      # ZMQ
      - '28332:28332'
    networks:
      - electrumx-network
    volumes:
      - ./data/bitcoinsv:/data
      - ./bitcoin.conf:/data/bitcoin.conf
    command: bitcoind -maxstackmemoryusageconsensus=20000000000 -excessiveblocksize=200000000000
    restart: always
networks:
  electrumx-network: